In [ ]:
import numpy as np       #addition
a=np.array([10,20,30])
b=np.array([5,10,15])
result=a+b
print(result)

#subtraction
import numpy as np
a=np.array([10,20,15])
b=np.array([5,7,4])
result = a-b
print(result)

print("__"*40)

#multiplication
import numpy as np
a=np.array([10,20,15])
b=np.array([5,7,4])
result = a*b
print(result)

print("__"*40)

#division
import numpy as np
a=np.array([100,200,300])
b=np.array([10,20,30])
res = a/b
print(res)

print("__"*40)

#modulus
import numpy as np
a=np.array([10,15,20])
b=np.array([3,4,6])
res = a%b
print(res)

print("__"*40)

#power
import numpy as np
a=np.array([10,12,15])
result = np.power(a,2)
print(result)

print("__"*40)

#square root
import numpy as np
a=np.array([64,81,225])
res = np.sqrt(a)
print(res)

print("__"*40)

#absolute value
import numpy as np
a=np.array([-10,-5,20,-30])
res = np.abs(a)
print(res)

print("__"*40)

#operations with scalar
import numpy as np
a=np.array([10,20,30])
print(a+5)

print("__"*40)
#matrix 2d
import numpy as np
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
C = A + B
print(C)
D = B - A
print(D)
print(np.matmul(A,B))

print("__"*40)

#Using @ opertor
import numpy as np
A=np.array([[2,3],
            [4,5]])

B=np.array([[1,2],
            [3,4]])

print(A @ B)

print("__"*40)

#3*3 mtrix
import numpy as np
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

B=np.array([[9,8,7],
            [6,5,4],
            [3,2,1]])

print(np.matmul(A,B))

print("__"*40)

#example
import numpy as np

sales=np.array([[10,20,30],
                [40,50,60]])

price=np.array([[100],
                [200],
                [300]])

total=np.matmul(sales,price)
print(total)

print("__"*40)

#transpose

import numpy as np

A=np.array([[10,20],
            [30,40]])

print(np.transpose(A))

print("__"*40)

#shape
import numpy as np
A=np.array([[1,2,3],
            [4,5,6]])

print(A.shape)
print(A.T.shape)

print("__"*40)

#mean
import numpy as np
marks=np.array([80,90,70,60,100])
print(np.mean(marks))

print("__"*40)

#mean (array)

import numpy as np
arr=np.array([[10,20],
              [30,40]])
print(np.mean(arr))

print("__"*40)
#mean by row

import numpy as np
arr=np.array([[10,20],
              [30,40]])

print(np.mean(arr,axis=1))

print("__"*40)

#mean by column
import numpy as np
arr=np.array([[10,20],
              [30,40]])

print(np.mean(arr,axis=0))

print("__"*40)

#median
import numpy as np
marks=np.array([80,90,70,60,100])
print(np.median(marks))

print("__"*40)
#standard deviation
import numpy as np
marks=np.array([10,20,30,40,50])
print(np.std(marks))

[15 30 45]
[ 5 13 11]
________________________________________________________________________________
[ 50 140  60]
________________________________________________________________________________
[10. 10. 10.]
________________________________________________________________________________
[1 3 2]
________________________________________________________________________________
[100 144 225]
________________________________________________________________________________
[ 8.  9. 15.]
________________________________________________________________________________
[10  5 20 30]
________________________________________________________________________________
[15 25 35]
________________________________________________________________________________
[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]
[[19 22]
 [43 50]]
________________________________________________________________________________
[[11 16]
 [19 28]]
________________________________________________________________________________
[[ 30  